services:
  emad_restapi:
    image: emad_restapi
    container_name: emad_restapi
    ports:
      - "8080:8080"
    environment:
      - IMAGES_URL_ROOT=http://localhost:9000/pictograms/pictograms/
      - CORE_URL_IT=http://emad_images-it:8080/
      - CORE_URL_EN=http://emad_images-en:8080/
      - DALLE3_ENDPOINT=https://example.home.arpa # change with the correct endpoint
      - DALLE3_APIKEY= # change with the correct api key
      - CLIENT_APIKEY=3352ca2b967b2ff415d5cecd978b1b25 # this is the default api key for the client
    depends_on:
      - minio_pictograms

  minio_pictograms:
    image: minio_pictograms
    container_name: minio_pictograms
    ports:
      - "9000:9000"

  mongodb:
    image: mongo
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=377eb8ec01c85fa727c10c478f60c13f
      - MONGO_INITDB_ROOT_PASSWORD=25d055a16b3d1a40d7a90e46bee02ef3
      - MONGO_INITDB_DATABASE=pictograms

  mongodb_setup:
    image: python:3.12-slim
    container_name: mongodb_setup
    depends_on:
      - mongodb
    restart: "no"
    volumes:
      - ./terraform/mongodb_data:/mongodb_data
    environment:
      - MONGODB_URI=mongodb://377eb8ec01c85fa727c10c478f60c13f:25d055a16b3d1a40d7a90e46bee02ef3@mongodb:27017
      - JSONS_DIR=/mongodb_data/jsons
    entrypoint: [ "/bin/bash", "-c", "apt update && apt install sudo dos2unix -y && dos2unix /mongodb_data/python_venv.sh && bash /mongodb_data/python_venv.sh /mongodb_data/create.py" ]

  emad_images-it:
    image: emad_images-it
    container_name: emad_images-it
    ports:
      - "8081:8080"
    environment:
      - MONGODB_URI=mongodb://377eb8ec01c85fa727c10c478f60c13f:25d055a16b3d1a40d7a90e46bee02ef3@mongodb:27017
      - MONGODB_DATABASE=pictograms
      - MONGODB_COLLECTION=pictograms
      - JSON_FILE=jsons/it.json
      - LANGUAGE=it
    depends_on:
      - mongodb_setup
      - mongodb

  emad_images-en:
    image: emad_images-en
    container_name: emad_images-en
    ports:
      - "8082:8080"
    environment:
      - MONGODB_URI=mongodb://377eb8ec01c85fa727c10c478f60c13f:25d055a16b3d1a40d7a90e46bee02ef3@mongodb:27017
      - MONGODB_DATABASE=pictograms
      - MONGODB_COLLECTION=pictograms
      - JSON_FILE=jsons/en.json
      - LANGUAGE=en
    depends_on:
      - mongodb_setup
      - mongodb
