{
 "title": "emad",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"env\",\r\n    predicate: (r) => true,\r\n    start: v.timeRangeStart, stop:v.timeRangeStop\r\n)"
    }
   },
   {
    "name": "path",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"path\",\r\n    predicate: (r) => true,\r\n    start: v.timeRangeStart, stop:v.timeRangeStop\r\n)"
    }
   },
   {
    "name": "language",
    "query": {
     "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"language\",\r\n    predicate: (r) => true,\r\n    start: v.timeRangeStart, stop:v.timeRangeStop\r\n)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of kewords",
   "type": "histogram",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"stats\")\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r.language =~ /${language:regex}/)\r\n  |> filter(fn: (r) => r._field == \"num_kw\")"
    }
   ]
  },
  {
   "title": "Number of keywords [${language}]",
   "type": "histogram",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 },
   "repeat": "language",
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"stats\")\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r.language =~ /${language:regex}/)\r\n  |> filter(fn: (r) => r._field == \"num_kw\")"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"perf\")\r\n  |> filter(fn: (r) => r.path =~ /${path:regex}/)\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r._field == \"latency\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"perf\")\r\n  |> filter(fn: (r) => r.path =~ /${path:regex}/)\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r._field == \"status_code\")"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"perf\")\r\n  |> filter(fn: (r) => r._field == \"status_code\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> group(columns: [\"_value\"])\r\n  "
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Core latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"stats\")\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r.language =~ /${language:regex}/)\r\n  |> filter(fn: (r) => r._field == \"latency\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Number of keywords",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"stats\")\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r.language =~ /${language:regex}/)\r\n  |> filter(fn: (r) => r._field == \"num_kw\")"
    }
   ]
  },
  {
   "title": "Filter sex content",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"stats\")\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r.language =~ /${language:regex}/)\r\n  |> filter(fn: (r) => r._field == \"filter_sex\")\r\n  |> map(fn: (r) => ({r with _value: if r._value then 1 else 0}))\r\n  |> keep(columns: [\"_value\"])\r\n  |> group(columns: [\"_value\"])\r\n  "
    }
   ]
  },
  {
   "title": "Filter violence content",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"stats\")\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r.language =~ /${language:regex}/)\r\n  |> filter(fn: (r) => r._field == \"filter_violence\")\r\n  |> map(fn: (r) => ({r with _value: if r._value then 1 else 0}))\r\n  |> keep(columns: [\"_value\"])\r\n  |> group(columns: [\"_value\"])\r\n  "
    }
   ]
  },
  { "title": "Keyword", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Most used keywords",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"keyword\")\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r.language =~ /${language:regex}/)\r\n  |> filter(fn: (r) => r._field == \"word\")\r\n  |> map(fn: (r) => ({ r with word: r._value, _value: 1 }))\r\n  |> group(columns: [\"word\", \"language\"])\r\n  |> sum()\r\n  |> sort()\r\n  |> limit(n: 20)\r\n"
    }
   ]
  },
  {
   "title": "Most not found keywords",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"keyword\")\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r.language =~ /${language:regex}/)\r\n  |> filter(fn: (r) => r._field == \"word\" or r._field == \"found\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => not bool(v: r.found))\r\n  |> map(fn: (r) => ({ r with word: r.word, _value: 1 }))\r\n  |> group(columns: [\"word\", \"language\"])\r\n  |> sum()\r\n  |> sort()\r\n  |> limit(n: 20)\r\n\r\n"
    }
   ]
  },
  {
   "title": "Keywords requested",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"keyword\")\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r.language =~ /${language:regex}/)\r\n  |> filter(fn: (r) => r._field == \"word\")\r\n  |> drop(columns: [\"env\", \"language\"])\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n"
    }
   ]
  },
  {
   "title": "keyword has sex content",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"keyword\")\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r.language =~ /${language:regex}/)\r\n  |> filter(fn: (r) => r._field == \"sex\")\r\n  |> map(fn: (r) => ({r with _value: if r._value then 1 else 0}))\r\n  |> keep(columns: [\"_value\"])\r\n  |> group(columns: [\"_value\"])\r\n\r\n  "
    }
   ]
  },
  {
   "title": "keyword has violence content",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"emad\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"keyword\")\r\n  |> filter(fn: (r) => r.env =~ /${env:regex}/)\r\n  |> filter(fn: (r) => r.language =~ /${language:regex}/)\r\n  |> filter(fn: (r) => r._field == \"violence\")\r\n  |> map(fn: (r) => ({r with _value: if r._value then 1 else 0}))\r\n  |> keep(columns: [\"_value\"])\r\n  |> group(columns: [\"_value\"])\r\n\r\n  "
    }
   ]
  }
 ]
}